default: &default
  adapter: postgresql
  encoding: unicode
  username: username
  password: password
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: gift_list_development

test:
  <<: *default
  database: gift_list_test
